- name: Prepare directories
  become: true
  shell: |
    mkdir -p /app
    chown ubuntu:ubuntu /app
- name: Copy source code
  copy:
    src: backend.tar.gz
    dest: /app
- name: Run backend service
  shell: |
    cd /app
    tar xf backend.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start