- name: Copy source code
  copy:
    src: backend.tar.gz
    dest: /
- name: Run backend service
  shell: |
    mkdir -p /app
    cd /app
    tar xf /backend.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start